### PR TITLE
Update hcert_spec.md

### PR DESCRIPTION
**Pull request by fredriklj**

### CODE REVIEW

**Comment by fredriklj** [comment]
Closes #31

**Review by jschlyter — APPROVED** [review]

**Comment by dirkx** [comment]
Resolved conflict on the date of the document.

**Review by dirkx — COMMENTED** [review]
Just fixing conflict on date in line 3

**Comment by asitplus-pteufl** [comment]
Can we add A-Z as well, 9 identifiers might not be enough. A-Z could also be used, but would drop the other chars from BASE45.

something like:
...SHALL define a new Context Identifier, whereas the character following "HC" SHALL be taken from the character sets [1-9] and [A-Z]. The order of increments is defined in the following order [1-9] and then [A-Z].

**Comment by fredriklj** [comment]
Good idea, fixed!

**Comment by dirkx** [comment]
Perfect !

**Pull request merged**
